import { IsEmail, IsNotEmpty, IsOptional, IsString, MaxLength } from 'class-validator';

export class CreateSupportMessageDto {
  @IsNotEmpty()
  @IsString()
  @MaxLength(100)
  name: string;

  @IsEmail()
  @MaxLength(200)
  email: string;

  @IsNotEmpty()
  @IsString()
  @MaxLength(2000)
  message: string;

  /** Groups messages from one widget session. Generated by the browser. */
  @IsOptional()
  @IsString()
  @MaxLength(64)
  conversationId?: string;

  /** Page the visitor was on, e.g. "/pricing". */
  @IsOptional()
  @IsString()
  @MaxLength(200)
  page?: string;

  /** Hidden field real visitors never fill in; bots usually do. */
  @IsOptional()
  @IsString()
  @MaxLength(200)
  website?: string;
}
